2025-06-03 16:24:00,157:DEBUG:certbot._internal.main:certbot version: 4.0.0
2025-06-03 16:24:00,159:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2025-06-03 16:24:00,160:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/var/www/certbot', '--agree-tos', '--email', 'diego.saldias.quijada@gmail.com', '-d', 'pgadmin.controldeprocesosquinta.com']
2025-06-03 16:24:00,160:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2025-06-03 16:24:00,216:DEBUG:certbot._internal.log:Root logging level set at 30
2025-06-03 16:24:00,222:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2025-06-03 16:24:00,223:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A separate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x777189634650>
Prep: True
2025-06-03 16:24:00,224:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x777189634650> and installer None
2025-06-03 16:24:00,224:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2025-06-03 16:24:00,370:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2433112377', new_authzr_uri=None, terms_of_service=None), b0b2ef532c4eb54439aad29ae6a1952e, Meta(creation_dt=datetime.datetime(2025, 5, 30, 23, 57, 18, tzinfo=datetime.timezone.utc), creation_host='eb839d63f696', register_to_eff=None))>
2025-06-03 16:24:00,383:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2025-06-03 16:24:00,404:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2025-06-03 16:24:00,618:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 1012
2025-06-03 16:24:00,619:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 03 Jun 2025 16:24:00 GMT
Content-Type: application/json
Content-Length: 1012
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "-KrTwW1oZL8": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "profiles": {
      "classic": "https://letsencrypt.org/docs/profiles#classic",
      "shortlived": "https://letsencrypt.org/docs/profiles#shortlived (not yet generally available)",
      "tlsserver": "https://letsencrypt.org/docs/profiles#tlsserver"
    },
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.5-February-24-2025.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2025-06-03 16:24:00,663:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for pgadmin.controldeprocesosquinta.com
2025-06-03 16:24:00,700:DEBUG:acme.client:Requesting fresh nonce
2025-06-03 16:24:00,700:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2025-06-03 16:24:00,776:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2025-06-03 16:24:00,777:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 03 Jun 2025 16:24:00 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: Yja0J4uheb6f7BcH0WzegJFeVEL4SLvKN_0JF5-jXtF1Aw1GHiw
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2025-06-03 16:24:00,781:DEBUG:acme.client:Storing nonce: Yja0J4uheb6f7BcH0WzegJFeVEL4SLvKN_0JF5-jXtF1Aw1GHiw
2025-06-03 16:24:00,781:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "pgadmin.controldeprocesosquinta.com"\n    }\n  ]\n}'
2025-06-03 16:24:00,796:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjQzMzExMjM3NyIsICJub25jZSI6ICJZamEwSjR1aGViNmY3QmNIMFd6ZWdKRmVWRUw0U0x2S05fMEpGNS1qWHRGMUF3MUdIaXciLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "JZjbc0WbLkNkHQZdCnktOeRzpwmHOuhW-5UqS2PkMQEHKDsIMxCNGGeG7LSjlWJMO0BqwtU3a5PhXav90r_iLyPEK_95E6nLA2sA0CHRmnrX5sY3yUDZwACiSuhWhnCpZhTD6z9rb8NHj3l2dt51M8joeETan2TqxvMZ2xC2ECU8e6Uhy3RZMZ291zokq1IzHqk8KtKSgj1ylvG34S1hmZ4AH0gKm8cmYsIilIxKGi5TTyXszc5-qUDv9EZ1vZi2PIZKHbF_XUPL0D3VXqGMFJk7WiqlotxeeyNWIb0jqct_J3ZuHB1kl5YFoBh46iY_-bhnofXQ0ss9SYZWIoIHhA",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInBnYWRtaW4uY29udHJvbGRlcHJvY2Vzb3NxdWludGEuY29tIgogICAgfQogIF0KfQ"
}
2025-06-03 16:24:00,894:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 429 316
2025-06-03 16:24:00,894:DEBUG:acme.client:Received response:
HTTP 429
Server: nginx
Date: Tue, 03 Jun 2025 16:24:00 GMT
Content-Type: application/problem+json
Content-Length: 316
Connection: keep-alive
Boulder-Requester: 2433112377
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://letsencrypt.org/docs/rate-limits>;rel="help"
Replay-Nonce: Yja0J4uhaGo8joxk8vsr6Sl40GczZo9dsjCJ3q36s4ekmpeyHOM
Retry-After: 416

{
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "too many failed authorizations (5) for \"pgadmin.controldeprocesosquinta.com\" in the last 1h0m0s, retry after 2025-06-03 16:30:56 UTC: see https://letsencrypt.org/docs/rate-limits/#authorization-failures-per-hostname-per-account",
  "status": 429
}
2025-06-03 16:24:00,898:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1872, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1578, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 523, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 424, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 484, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem, profile=profile)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 143, in new_order
    response = self._post(self.directory['newOrder'], order)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 369, in _post
    return self.net.post(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 741, in post
    return self._post_once(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 754, in _post_once
    response = self._check_response(response, content_type=content_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 605, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: too many failed authorizations (5) for "pgadmin.controldeprocesosquinta.com" in the last 1h0m0s, retry after 2025-06-03 16:30:56 UTC: see https://letsencrypt.org/docs/rate-limits/#authorization-failures-per-hostname-per-account
2025-06-03 16:24:00,927:ERROR:certbot._internal.log:An unexpected error occurred:
2025-06-03 16:24:00,927:ERROR:certbot._internal.log:too many failed authorizations (5) for "pgadmin.controldeprocesosquinta.com" in the last 1h0m0s, retry after 2025-06-03 16:30:56 UTC: see https://letsencrypt.org/docs/rate-limits/#authorization-failures-per-hostname-per-account
